### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 2772: character maps to <undefined>

### ISSUE THREAD

**Issue by SaierLaboratory** [libChEBI/libChEBIpy#28]
Dear developers,

We were working in December with the libChEBIpy library without any problems, however this year our scripts keep crashing. We are running the code on iMacs (MacOS  Ventura, Big Sur and Catalina; running Python 3.8, 3.9, 3.10 and 3.11), with the same error message in all cases. 

You can easily reproduce the error with a 2-line code, which produces the error message below (note that no modifications to the code have been made since December). Can you give us any advice on what to do to fix this new issue?

**Test code:**

import libchebipy
c=libchebipy.ChebiEntity("29108")

**Generates the error:**

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/anaconda3/lib/python3.8/site-packages/libchebipy/_chebi_entity.py", line 30, in __init__
        if self.get_name() is None:
      File "/usr/local/anaconda3/lib/python3.8/site-packages/libchebipy/_chebi_entity.py", line 93, in get_name
        name = parsers.get_name(self.__chebi_id)
      File "/usr/local/anaconda3/lib/python3.8/site-packages/libchebipy/_parsers.py", line 242, in get_name
        __parse_compounds()
      File "/usr/local/anaconda3/lib/python3.8/site-packages/libchebipy/_parsers.py", line 294, in __parse_compounds
        for line in textfile:
      File "/usr/local/anaconda3/lib/python3.8/encodings/cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
     UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 2772: character maps to <undefined>

Many thanks in advance!!

**Comment by zas97** [comment]
I have exactly the same problem. The code was working last year and now gives this without updates to the library. I'm guessing that there is a problem with database

**Comment by seankim658** [comment]
Having this issue as well. I've been working around it by not using this library and just hitting the endpoint (https://www.ebi.ac.uk/webservices/chebi/2.0/test/getCompleteEntity?chebiId={id}) manually with the requests library and then just parsing the return XML.
